### ISSUE TITLE
Windows Phone support?

### ISSUE THREAD

**Issue by ramsestom** [shannah/cn1-data-access-lib#1]
Hi Steve

   You tell that your library should work with windows phone. However, I thought SQLite and codenameone Database class where not supported on the Windows Phone platform. So do you use your own api to store objects in a database on windows phone or is the codenameone Database class compatible with WP now?

**Comment by shannah** [comment]
Thanks for pointing this out.  I haven't tested on WinPhone - I didn't realize that SQLite wasn't implemented on it yet.  I'll be setting up a windows development environment over the next couple of weeks and I'll see if there's something I can do for that.
