### ISSUE TITLE
Could you update the plugin so that it map/unmap recursively ?

### ISSUE THREAD

**Issue by JrmyDev** [shannah/cn1-data-access-lib#2]
Actually, if you have 2 tabs in you database : Company and Employee.
The Company is joined with employee. I would like, when I retrieve a company object, that it retrieve also the linked employee. 

Thanks in advance.

**Comment by shannah** [comment]
So you have a 1-n relationship from company to employee, and when you load a company, you want to load all of its employees?  Generally I handle something like that by implementing a custom Company class and associated CompanyDAO.  Company has a list of employees, that you can populate using the CompanyDAO.  Generally I find it better to make the "loadEmloyees" method separate from just loading the company.

**Comment by JrmyDev** [comment]
Sorry It's not what I meant... 
I take another example, you have 2 tables : Employee and EmployeeProfil (which contains basics informations of an employee). There is a 1-1 relationship between the tables. I would like to retrieve both the employee and basics informations associated. 

1) Employee : id - job - idEmployeeProfil  
2) EmployeeProfil : id - name - surname - idEmployee

When I recover Employee (id = 10; job = "financial director" - idEmployeeProfil = 2) , I would like it recover the "EmployeeProfil" where id="2".

It's the same approach of hibernate : it retrieve automatically the linked tables.
Thanks.

**Comment by shannah** [comment]
Currently a DAO just maps to one table.  However, you can derive the DAO and implement your own loader methods that issue a custom SQL query that uses your Join, then populate both data objects at the same time.

E.g. Use the db() method to obtain a reference to the database. Use fillMap(Cursor,Map) to get the row values specific to a particular DAO.  This isn't terribly hard to do, but I am open to suggestions for APIs make this use case easier.

**Comment by JrmyDev** [comment]
Actually, I derive the DAO for each class of my model as you suggest in the readme. I would like to avoid custom SQL Query, that's why I asked you this update. I thought there was solution to retrieve recursively joined tables ! No matter, thanks for your help :)
