### ISSUE TITLE
NumberFormatException when loading a DB setup file

### ISSUE THREAD

**Issue by Isborg** [shannah/cn1-data-access-lib#5]
I get an exception when the database version is parsed to an Integer because the string it tries to parse is "1\r". Looking into it, I found that Windows uses \r\n for line breaks and the string from the setup file separates lines at \n, leaving the carriage return character in there.

I just removed the carriage returns "\r" with a hex editor and it works fine after that. This is in the DAOProvider class, loadDatabaseSQL method, line 118.

**Comment by kaya1923** [comment]
i did fix this for me with calling the String trim() Method.

For this i had to install Netbeans, import project, fix the line and build, unfortunately i was not able to run this in eclipse.

But hey for anyone else, here is my build file to save the hassle.
If i would understand how github works i would have fixed and commited this line, sorry guys...

[CN1DataAccess.zip](https://github.com/shannah/cn1-data-access-lib/files/277067/CN1DataAccess.zip)

**Comment by Nightbringer42** [comment]
I've added a pull request for this line.
