### ISSUE TITLE
is it compulsory to have 'id' column in each table?

### ISSUE THREAD

**Issue by akash-more4apps** [shannah/cn1-data-access-lib#7]
I tested couple of times and ended up (by looking in to fetchAll() code) with adding id column in my table.

If I remove that id column then its giving me NullPointerError when I do fetchAll().

Please can you say is it compulsory to have id column in each and every table?

**Comment by shannah** [comment]
Yes.

https://github.com/shannah/cn1-data-access-lib#limitations-and-constraints
