### ISSUE TITLE
can I retrieve data from 2 table.

### ISSUE THREAD

**Issue by akash-more4apps** [shannah/cn1-data-access-lib#8]
I have 2 tables as below

- Table1            
Col1_1  ,  Col1_2  ,  Col1_3 

- Table2
Col2_1 ,  Col2_2 ,  Col2_3

I want few data from both the tables, like,

SELECT 
  t1.Col1_1 , t1.col1_2 , 
  t2.col2_2 ,  t2.col2_3 
FROM Table1 t1, Table2 t2
WHERE t1.col1_3 = t2.col2_3 

Based on the example given in doc I am able to get either records of T1 or T2 but not both by one query.

Please can you help how to retrieve this.

Thanks,
Akash

**Comment by shannah** [comment]
Currently DAO is meant to be used on a single table.
